### ISSUE TITLE
how to generator feature map visualization?

### ISSUE THREAD

**Issue by Junhyuk93** [naver-ai/GGDR#2]
Is there a way to get the visualization image of the intermediate feature map? (As shown in Figure 15.~ 17. in the paper)

I would like to check the change of feature map according to the progress of training.

i look forward to your reply. Thank you!

**Comment by gylee1103** [comment]
Hi, I added visualization codes in [tools/visualize_gfeat.py](https://github.com/naver-ai/GGDR/blob/main/tools/visualize_gfeat.py).
It needs [kmeans_pytorch](https://github.com/subhadarship/kmeans_pytorch) library. You can save the model during training and separately run the visualization.

**Comment by Junhyuk93** [comment]
It is working well!! Thank you for your kind explanation.

I hope you have a good day. 😊
